---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-rebalancer-leader-election-rolebinding
  namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-rebalancer-leader-election-role
subjects:
  - kind: ServiceAccount
    name: pod-rebalancer-controller-manager
    namespace: system
